routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::group(['middleware' => ['auth:sanctum', 'verified']], function (){
    Route::view('/dashboard', 'dashboard')->name('dashboard');

    Route::resource('department', DepartmentController::class);

    Route::resource('position', PositionController::class);

    Route::resource('user', UserController::class);
    Route::get('user/{user}/change_password', [UserController::class, 'change_password'])->name('user.change_password');
    Route::post('user/{user}/change_password', [UserController::class, 'change_password_store'])->name('user.change_password.store');
    Route::get('user/{user}/digital_signature', [UserController::class, 'digital_signature'])->name('user.digital_signature');
    Route::post('user/{user}/digital_signature', [UserController::class, 'digital_signature_store'])->name('user.digital_signature.store');

    Route::put('user/profile/update-personal-information', [UserController::class, 'updateProfile'])->name('user.update_profile');
    Route::put('user/profile/change-password', [UserController::class, 'updatePersonalPassword'])->name('user.update_password');

    Route::resource('document', DocumentController::class);
    Route::post('document/{document}/approve', [DocumentController::class, 'approve'])->name('document.approve');
    Route::get('document/{document}/pdf', [DocumentController::class, 'exportPdf'])->name('document.pdf');

    Route::get('item/json', [ItemController::class, 'getDataAsJson'])->name('item.getAsJson');
});

Route::view('pdf/view','pages.document.view_pdf');

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Uuids;
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasRoles;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'department_id',
        'password',
        'digital_signature'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function department()
    {
        return $this->belongsTo(Department::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Repositories\DepartmentRepository;
use App\Repositories\UserRepository;
use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    protected $userService, $userRepository;

    public function __construct()
    {
        $this->userRepository = new UserRepository();
        $this->userService = new UserService();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()){
            return $this->userService->getDatatables();
        }

        return view('pages.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.user.create', $this->userService->showPositionAndDepartment());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'name',
            'email',
            'password',
            'password_confirmation',
            'department_id',
            'position_id'
        ]);

        try {
            if ($request->hasFile('digital_signature')){
                $data['digital_signature'] = $this->userService->uploadDigitalSignature($request->only(['digital_signature']), $request->file('digital_signature')->getClientOriginalExtension());
            }else{
                $data['digital_signature'] = '';
            }

            $this->userService->saveData($data);
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('user.index')->withMessage('Add user successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|void
     */
    public function edit(User $user)
    {
        return view('pages.user.edit', array_merge(['data' => $user], $this->userService->showPositionAndDepartment()));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = $request->only([
            'name',
            'email',
            'department_id',
            'position_id'
        ]);

        try {
            $this->userService->updateData($data, $user);
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('user.index')->withMessage('Update user successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User $user)
    {
        try {
            $this->userRepository->delete($user);
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage());
        }

        return back()->withMessage('Delete user successfully');
    }

    public function change_password(User $user)
    {
        return view('pages.user.change_password',[
            'data' => $user
        ]);
    }

    public function change_password_store(Request $request, User $user)
    {
        $data = $request->only([
            'password',
            'password_confirmation',
        ]);

        try {
            $this->userService->changePasswordUser($data, $user);
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('user.index')->withMessage('Change password successfully');
    }

    public function digital_signature(User $user)
    {
        return view('pages.user.digital_signature',[
            'data' => $user
        ]);
    }

    public function digital_signature_store(Request $request, User $user)
    {
        $data = [];

        try {
            if ($request->hasFile('digital_signature')){
                $data['digital_signature'] = $this->userService->updateDigitalSignature($request->only(['digital_signature']), $request->file('digital_signature')->getClientOriginalExtension(), $user);
            }else{
                $data['digital_signature'] = '';
            }

            $this->userService->updateData($data, $user);
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('user.index')->withMessage('Upload digital signature successfully');
    }

    public function updateProfile(Request $request)
    {
        try {
            $this->userService->updatePersonalData($request->except('_token'), Auth::user());
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return back()->withMessage('Update personal information successfully');
    }

    public function updatePersonalPassword(Request $request)
    {
        try {
            $this->userService->changePersonalPasswordUser($request->except('_token'), Auth::user());
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('profile.show')->withMessage('Update personal information successfully');
    }
}

resources/views/pages/user/change_password.blade.php
@extends('layouts.master')
@section('title', 'Change Password User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Change Password</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
            <span class="text-muted">User</span>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('user.index') }}" class="text-muted">List</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">Change Password</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-10 col-12">
            <div class="card card-custom">
                <div class="card-header flex-wrap">
                    <div class="card-title">
                        <h3 class="card-label">Change Password</h3>
                    </div>
                </div>

                <div class="card-body">
                    <form action="{{ route('user.change_password.store', $data) }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>New Password</label>
                                    <input type="password" class="form-control" placeholder="Password" name="password" value="" autocomplete="new-password" required/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Confirm Password</label>
                                    <input type="password" class="form-control" placeholder="Confirm Password" name="password_confirmation" value="" required/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button class="btn btn-success btn-block">Change Password</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/user/create.blade.php
@extends('layouts.master')
@section('title', 'Add New User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Add New</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        {{--        <li class="breadcrumb-item">--}}
        {{--            <a href="" class="text-muted">Features</a>--}}
        {{--        </li>--}}
        <li class="breadcrumb-item">
            <span class="text-muted">User</span>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('user.index') }}" class="text-muted">List</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">Add New</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-10 col-12">
            <div class="card card-custom">
                <div class="card-header flex-wrap">
                    <div class="card-title">
                        <h3 class="card-label">Add New</h3>
                    </div>
                </div>

                <div class="card-body">
                    <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" class="form-control" placeholder="Name" name="name" value="{{ old('name') }}" required autocomplete="new-name" autofocus/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" placeholder="Email" name="email" value="{{ old('email') }}" autocomplete="new-email" required/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-12">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" placeholder="Password" name="password" value="" autocomplete="new-password" required/>
                                </div>
                            </div>
                            <div class="col-sm-6 col-12">
                                <div class="form-group">
                                    <label>Confirm Password</label>
                                    <input type="password" class="form-control" placeholder="Confirm Password" name="password_confirmation" value="" required/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Department</label>
                                    <select name="department_id" id="department_id" class="form-control" required>
                                        <option value=""></option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->id }}" {{ old('department_id') == $department->id ? 'selected' : '' }}>{{ $department->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Position</label>
                                    <select name="position_id" id="position_id" class="form-control" required>
                                        <option value=""></option>
                                        @foreach($positions as $position)
                                            <option value="{{ $position->name }}" {{ old('position_id') == $position->name ? 'selected' : '' }}>{{ $position->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
{{--                        <div class="row">--}}
{{--                            <div class="col-12">--}}
{{--                                <div class="form-group">--}}
{{--                                    <label>Digital Signature</label>--}}
{{--                                    <input type="file" accept="image/*" class="form-control" placeholder="Digital Signature" name="digital_signature" required autofocus/>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
                        <div class="row">
                            <div class="col-md-12">
                                <button class="btn btn-success btn-block">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js-script')
    <script>
        $(document).ready(function () {
            $('#department_id').select2({
                placeholder: "Select a department",
                allowClear: true
            });
            $('#position_id').select2({
                placeholder: "Select a position",
                allowClear: true
            });
        });
    </script>
@endpush

resources/views/pages/user/digital_signature.blade.php
@extends('layouts.master')
@section('title', 'Upload Digital Signature User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Upload Digital Signature</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
            <span class="text-muted">User</span>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('user.index') }}" class="text-muted">List</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">Upload Digital Signature</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-10 col-12">
            <div class="card card-custom">
                <div class="card-header flex-wrap">
                    <div class="card-title">
                        <h3 class="card-label">Upload Digital Signature</h3>
                    </div>
                </div>

                <div class="card-body">
                    <form action="{{ route('user.digital_signature.store', $data) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Upload New Digital Signature</label>
                                    <input type="file" accept="image/*" class="form-control" placeholder="Digital Signature" name="digital_signature" id="digital_signature" required autofocus/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-center">
                                <div class="form-group">
                                    <img src="{{ $data->digital_signature ? asset('storage/user/'.$data->digital_signature) : asset('assets/media/no-image.jpeg') }}" width="200px" alt="{{ $data->digital_signature ?? 'no image' }}" id="preview_image">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button class="btn btn-success btn-block">Upload</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js-script')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#preview_image').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#digital_signature").change(function(){
            readURL(this);
        });
    </script>
@endpush

resources/views/pages/user/edit.blade.php
@extends('layouts.master')
@section('title', 'Edit User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Edit</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        {{--        <li class="breadcrumb-item">--}}
        {{--            <a href="" class="text-muted">Features</a>--}}
        {{--        </li>--}}
        <li class="breadcrumb-item">
            <span class="text-muted">User</span>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('user.index') }}" class="text-muted">List</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">Edit</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-10 col-12">
            <div class="card card-custom">
                <div class="card-header flex-wrap">
                    <div class="card-title">
                        <h3 class="card-label">Edit</h3>
                    </div>
                </div>

                <div class="card-body">
                    <form action="{{ route('user.update', $data) }}" method="POST" enctype="multipart/form-data">
                        @csrf @method('PATCH')
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" class="form-control" placeholder="Name" name="name" value="{{ $data->name ?? old('name')  }}" required autocomplete="new-name" autofocus/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" placeholder="Email" name="email" value="{{ $data->email ?? old('email') }}" autocomplete="new-email" required/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Department</label>
                                    <select name="department_id" id="department_id" class="form-control" required>
                                        <option value=""></option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->id }}" {{ ($data->department_id ?? old('department_id')) == $department->id ? 'selected' : '' }}>{{ $department->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Position</label>
                                    <select name="position_id" id="position_id" class="form-control" required>
                                        <option value=""></option>
                                        @foreach($positions as $position)
                                            <option value="{{ $position->name }}" {{ ($data->roles->pluck('name')[0]  ?? old('position_id')) == $position->name ? 'selected' : '' }}>{{ $position->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button class="btn btn-success btn-block">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js-script')
    <script>
        $(document).ready(function () {
            $('#department_id').select2({
                placeholder: "Select a department",
                allowClear: true
            });
            $('#position_id').select2({
                placeholder: "Select a position",
                allowClear: true
            });
        });
    </script>
@endpush

resources/views/pages/user/index.blade.php
@extends('layouts.master')
@section('title', 'User')

@push('css-style')
    <link href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css') }}" rel="stylesheet" type="text/css" />
@endpush

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Lists</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
            <a href="" class="text-muted">User</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">List</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">List User</h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{ route('user.create') }}" class="btn btn-success font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                    <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <rect x="0" y="0" width="24" height="24"/>
                            <circle fill="#000000" cx="9" cy="15" r="6"/>
                            <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"/>
                        </g>
                    </svg>
                    <!--end::Svg Icon-->
                </span>Add new
                </a>
                <!--end::Button-->
            </div>
        </div>

        <div class="card-body">
            <table class="table table-separate table-head-custom table-checkable" id="datatable">
                <thead>
                <tr>
                    <th>No</th>
                    <th>User Name</th>
                    <th>Email</th>
                    <th>Department</th>
                    <th>Digital Signature</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>

        </div>
    </div>
@endsection

@push('js-script')
    <script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable({
                scrollX: true,
                processing: true,
                serverSide: true,
                ajax: "{{ route('user.index') }}",
                columns: [
                    {data: null, sortable: false, searchable: false,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'department_name', name: 'department_name'},
                    {data: 'digital_signature', name: 'digital_signature', render(data) {
                            if (data){
                                return "<center><div class='badge badge-success'>EXIST</div></center>";
                            }else{
                                return "<center><div class='badge badge-danger'>NOT EXIST</div></center>";
                            }
                        }
                    },
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            })
        });
    </script>
@endpush